### ISSUE TITLE
Check QC notebooks

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/dynamicrouting-summary#1]
QC notebooks can be found here - use the latest version subfolder, currently `v0.0.176`: 
https://osf.io/9237b/?view_only=035876aa04154f04ab5ca1e6be18ee72

- [x] download all files as zip file (or just accept the slow loading and work with them in the browser)
- [x] go through each one and keep a record of files that have errors with a traceback, for example:
  ![image](https://github.com/AllenInstitute/dynamicrouting-summary/assets/63425812/0e211bae-ae6a-4caf-94a3-cf81303e42f5)
  - if there's an error that's present for all sessions, just ignore it

**Comment by hcabasco** [comment]
should i look under a specific version, i.e. v.0.0.176? seeing the same sessions multiple places

**Comment by bjhardcastle** [comment]
In each `v?.?.?` folder there should be one notebook for each session.

And we just want to use the latest version of the notebooks (`v0.0.176`)

**Comment by hcabasco** [comment]
[qc-sessions.csv](https://github.com/AllenInstitute/dynamicrouting-summary/files/14027997/qc-sessions.csv)

done. list of sessions is in the file above.

**Comment by bjhardcastle** [comment]
What were the most common errors?

**Comment by hcabasco** [comment]
1. in stim timing, ValueError: Expected the given number of width ratios to match the number of columns of the grid
2. in stim timing, TypeError: 'Axes' object is not iterable
3. in MVR, AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by hcabasco** [comment]
i also noticed some ephys sessions that don't have qc notebooks present here. are you already aware of these?

**Comment by bjhardcastle** [comment]
Possibly.. any sessions with `issues` here are skipped:
https://github.com/alleninstitute/npc_lims/blob/main/tracked_sessions.yaml
