### ISSUE TITLE
Make functions to add session bool columns from `npc_lims`

### ISSUE THREAD

**Issue by bjhardcastle** [AllenInstitute/dynamicrouting-summary#2]
Each row in one of our cached parquet dataframes has `subject_id: int`, `date: datetime[day]`, `session_idx: int` columns, which can be used to access the following bools with `npc_lims.get_session_info(f"{subject_id}_{date}_{session_idx}")`:
- [x] `is_templeton` (`False` implies DynamicRouting)
- [x] `is_ephys`
- [x] `is_training`

Add these columns to each row in a dataframe with:

```python
def add_bool_columns(df: pd.DataFrame) -> pd.DataFrame:
   ...
```

This should be a 15 minute job - if it's taking longer let me know.

**Comment by arjunsridhar12345** [comment]
@bjhardcastle i'm not seeing is_training bool as part of session info object. Is there some other way to get it or am i just missing something?

**Comment by bjhardcastle** [comment]
Ah yeah, it doesn't exist.. just `is_ephys`
